name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: cd 1_unit/jest/ && npm i
      - name: Run tests
        run: npm test
